# Generated by Django 4.0.4 on 2022-06-11 23:53

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('data', models.DateField(default='2022-06-12')),
                ('titulo', models.CharField(max_length=75)),
                ('descricao', models.TextField()),
                ('urlProjetoOuPortfolio', models.URLField(blank=True, default='', null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=portfolio.models.resolution_path)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=57)),
                ('local', models.CharField(max_length=20)),
                ('cursoFrequentado', models.CharField(max_length=31)),
                ('periodoNaInstituicao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to=portfolio.models.resolution_path)),
                ('link', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75)),
                ('descricao', models.TextField()),
                ('link', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linguagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('linkNoticia', models.URLField(blank=True, default='', null=True)),
                ('imagem', models.ImageField(blank=True, upload_to=portfolio.models.resolution_path)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('linkDaPessoaLusofona', models.URLField(blank=True, default='', null=True)),
                ('linkDaPessoaLinkedIn', models.URLField(blank=True, default='', null=True)),
                ('linkPortfolioPW', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pontuacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeExtenso', models.CharField(max_length=75)),
                ('sigla', models.CharField(max_length=10)),
                ('anoDeCriacao', models.IntegerField()),
                ('criador', models.CharField(max_length=115)),
                ('linkSiteOficial', models.URLField(blank=True, default='', null=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
                ('imagem', models.ImageField(blank=True, upload_to=portfolio.models.resolution_path)),
                ('anoLetivoEmQueFoiRealizado', models.CharField(blank=True, default='2020/21', max_length=15, null=True)),
                ('linkGitHub', models.URLField(blank=True, default='', null=True)),
                ('linkVideoYoutube', models.URLField(blank=True, default='', null=True)),
                ('linguagemUtilizada', models.ManyToManyField(related_name='linguagemUsada', to='portfolio.linguagen')),
                ('participantes', models.ManyToManyField(blank=True, null=True, related_name='participantes', to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=57)),
                ('ano', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('semestre', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('anoLetivoFrequentado', models.CharField(max_length=15)),
                ('ects', models.IntegerField(default=1)),
                ('descricao', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('urlCadeira', models.URLField(blank=True, default='', null=True)),
                ('docente_praticas', models.ManyToManyField(related_name='praticas', to='portfolio.pessoa')),
                ('docente_teorica', models.ManyToManyField(related_name='teoricas', to='portfolio.pessoa')),
                ('linguagens', models.ManyToManyField(related_name='linguagem', to='portfolio.linguagen')),
                ('projetos', models.ManyToManyField(blank=True, null=True, related_name='projeto', to='portfolio.projeto')),
            ],
        ),
    ]
