# Generated by Django 4.0.4 on 2022-06-12 00:04

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_projeto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=portfolio.models.resolution_path),
        ),
    ]
