# Generated by Django 4.0.4 on 2022-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projeto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptidoesECompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75)),
                ('descricaoCurta', models.TextField(max_length=250)),
                ('listaDisciplinas', models.ManyToManyField(blank=True, null=True, related_name='disciplinas', to='portfolio.cadeira')),
                ('listaProjetos', models.ManyToManyField(blank=True, null=True, related_name='projetos', to='portfolio.projeto')),
            ],
        ),
    ]
